# Permalinks
permalink:           pretty

# Setup
exclude:             [CNAME, Gemfile, README.md, LICENSE.md, scratch.md]
unpublished:         true
show_drafts:         false
title:               Bae's Blog
tagline:             Standing on the shoulders of giants
description:         'A blog to memorize and note'
url:                 https://toodifficulto.github.io/
baseurl:             ''

# About/contact
author:
  name:              Seung Hak Bae
  url:               https://toodifficulto.github.io/
  email:

# Custom data
established:         
license:
license_url:
