# Permalinks
#
permalink:           pretty

# Setup
title:             Bae's Blog
tagline:             'standing on the shoulder of giants'
description:         <img src = "/public/apple-touch-icon-precomposed.png"> 거인의 어꺠 위에서, 세상 훔쳐보기
url:                 https://toodifficulto.github.io/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Seung Hak Bae
  url:               https://toodifficulto.github.io/
  email:

# Custom vars
version:             1.0.0
